### ISSUE TITLE
可以把Demo的数据库脚本放出来吗？

### ISSUE THREAD

**Issue by xier2012** [VictorTzeng/Zxw.Framework.NetCore.Demo#1]
可以把Demo的数据库脚本公布出来吗？

**Comment by VictorTzeng** [comment]
运行起来后，如下操作：
1.往SysUser表造一条数据
2.在浏览器地址栏执行Home/Init，初始化系统模块数据
3.打开登录界面，登录就好了

**Comment by mydiycode** [comment]
mysql数据库，项目启动之后只创建了数据库，没有创建表，不知道什么情况？

**Comment by VictorTzeng** [comment]
有在浏览器地址栏访问home/init吗？如果执行了，还没有的话，建议打断点调试下代码

**Comment by mydiycode** [comment]
正常情况不是应该启动项目就生成了表吗，执行home/init是初始化表数据吧。执行home/init的时候调试是找不到表。
![image](https://user-images.githubusercontent.com/5533118/60002919-36cd4e80-969c-11e9-8be5-33a7bc7b13ed.png)

**Comment by javinjiao** [comment]
@mydiycode @VictorTzeng 解决了吗？我这也是同样的错误
