### ISSUE TITLE
 EF.Functions.Contains执行时需要创建全文索引

### ISSUE THREAD

**Issue by newbking** [VictorTzeng/Zxw.Framework.NetCore.Demo#10]
在HomeController的93行menuRepository.Count(m => EF.Functions.Contains(m.Identity, parentIdentity))执行时需要创建全文索引，个人觉得应该改成menuRepository.Count(m =>m.Identity.Contains(parentIdentity))

**Comment by VictorTzeng** [comment]
你可以改成Contains试试，欢迎提PR~

**Comment by newbking** [comment]
本人菜鸟不敢动大牛代码，我已经测试过可行，不需要创建全文索引
