### ISSUE TITLE
创建表报错Cannot create a DbSet for 'SysUser' because this type is not included in the model for the context

### ISSUE THREAD

**Issue by smilexlong** [VictorTzeng/Zxw.Framework.NetCore.Demo#7]
我按照你的demo配置的，不过中间多加了一层service
image
![image](https://user-images.githubusercontent.com/19772709/61114177-5ea51a80-a4c2-11e9-9395-15dcb5d21b4e.png)

image
![image](https://user-images.githubusercontent.com/19772709/61114188-6664bf00-a4c2-11e9-9bfd-99b17b7caab5.png)

image
![image](https://user-images.githubusercontent.com/19772709/61114211-6cf33680-a4c2-11e9-9358-8eff4acf1467.png)

在配置里也注入了service, 但是启动项目不会立刻创建数据库，而是在调用了一个接口进入controller的方法后才会创建数据库，但是创建的是空数据库，没有表，而且报错
image
![image](https://user-images.githubusercontent.com/19772709/61114220-767c9e80-a4c2-11e9-8e6d-3001f097ceba.png)
这个大概是什么原因导致的？

**Comment by VictorTzeng** [comment]
在sysuer类上标记你的数据库上下文 [DbContext(typeof(SqlServerDbContext))]

**Comment by smilexlong** [comment]
谢谢，有了，不报错了。  还有个小问题咨询下，我看你的项目是运行了就会创建数据库和表。我这边必须的第一次必须的调用一下Repository才会创建，这个是什么导致的？

**Comment by VictorTzeng** [comment]
@smilexlong 首先你得跟数据库打交道，才会有生成数据库的操作

**Comment by smilexlong** [comment]
嗯，那我写个初始化数据的类单独调用下，你这个根据实体类升级数据库是怎么操作的？

**Comment by VictorTzeng** [comment]
@smilexlong 数据迁移这块儿，测试环境还是粗暴点，直接删库重新生成。如果要用EF core的命令行做数据迁移的话，先得自定义个DbContext继承项目中的一个DbContext（比如SqlServerDbConext），然后参照ef core的迁移指令文档进行迁移操作。
