### ISSUE TITLE
mysql

### ISSUE THREAD

**Issue by WangBank** [VictorTzeng/Zxw.Framework.NetCore.Demo#8]
MySql.Data.MySqlClient.MySqlException:“Incorrect table definition; there can be only one auto column and it must be defined as a key”
![image](https://user-images.githubusercontent.com/40753996/65003790-8f735700-d92c-11e9-9c41-60779732921d.png)

**Comment by VictorTzeng** [comment]
组合主键？？

**Comment by WangBank** [comment]
操作流程：

**Comment by WangBank** [comment]
操作流程：1下载demo  2 将sqlserver改为mysql还有字符串  3 运行 报错 ，已经自动生成数据库 ，是在生成表的时候报的错

**Comment by VictorTzeng** [comment]
DbContext有修改吗

**Comment by VictorTzeng** [comment]
mysql对字段的长度要求非常严格，需要对每个字段做调整

**Comment by WangBank** [comment]
看着报错原因是user表中有两个自增键，但是我没找到在哪设置的
