### ISSUE TITLE
执行Home/Init报错

### ISSUE THREAD

**Issue by newbking** [VictorTzeng/Zxw.Framework.NetCore.Demo#9]
The LINQ expression 'DbSet<SysMenu>
    .Count(s => s.Identity.Equals(
        value: __identity_0, 
        comparisonType: OrdinalIgnoreCase))' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to either AsEnumerable(), AsAsyncEnumerable(), ToList(), or ToListAsync().
代码在HomeController的110行

**Comment by VictorTzeng** [comment]
fixed。请拉取最新代码。这是因为在efcore 3.0+中lambda表达式不支持equals

**Comment by newbking** [comment]
大佬，在93行的EF.Functions.Contains(m.Identity, parentIdentity)执行时需要创建全文索引，我是手动创建的，是否可以应该换成linq？
